kv:
  query_cmd: ./example-files/query.sh --abc
  adjust_cmd: ./example-files/adjust.sh
  components:
    canary:
      settings:
        memory:
          type: range
          min: 1
          max: 5
          step: .1
          unit: GiB
        cpu:
          type: range
          min: .1
          max: 4
          step: .1
          unit: cores
        replicas:
          type: range
          min: 1
          max: 10
          step: 1
          unit: count
        load_balancer:
          type: enum
          values:
            - least_connections
            - round_robin
          unit: LB Type
      env:
        JAVA_ARGS:
          encoder:
            name: jvm
            before:
              - "/app.sh"
            settings:
              GCTimeRatio:
                default: 75
                step: 15
            after:
              - "-v"
        N_DB_CONN: 100
